---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gloo-gateway-config
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m0s
  retryInterval: 2m0s
  prune: true
  suspend: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: platform-team
  path: "./gloo-gateway-config/cluster2"
